import { defineConfig } from "tsup";

export default defineConfig({
  entry: ["src/index.ts"],
  outDir: "dist",
  format: ["cjs"], // Works great with Electron
  dts: true,
  external: ["node-swift"],
  clean: true,
  sourcemap: true,
  splitting: false, // Keep false for native modules
  target: "node16",
  platform: "node",
  bundle: true,
  minify: false, // Keep false for native modules to avoid issues
  keepNames: true,
  skipNodeModulesBundle: true,
  noExternal: [], // Don't bundle any external deps

  // Handle .node files (copy them as-is)
  loader: {
    ".node": "copy",
  },

  banner: {
    js: "// Generated by tsup - Node-AXKit Native Module",
  },

  define: {
    "process.env.NODE_ENV": JSON.stringify(process.env.NODE_ENV || "production"),
  },

  esbuildOptions: (options) => {
    options.keepNames = true; // Preserve original function names for native interop
    options.platform = "node";

    // Don't resolve .node files
    options.external = options.external || [];
    options.external.push("*.node");
  },

  onSuccess: async () => {
    console.log("✅ TypeScript build completed successfully!");
    console.log("💡 Remember to run copy:native to bundle Module.node");
  },
});
